name: TruffleHog Secrets Scan
on: [push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout 
        uses: addnab/docker-run-action@v3
        with:
          image: zricethezav/gitleaks
          shell: bash
          options: -u 0 -v ${{ github.workspace }}:/src
          run: |
            gitleaks detect --source=/src --verbose --no-git --report-path gitleaks-reports.json
            cat gitleaks-reports.json
            pwd
            ls
      - name: putses   
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: gitleaks-reports.json
            
            
            
            
   
       
