name: TruffleHog Secrets Scan
on: [push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout
        run: |
            docker run --user 0 --volume ${{ github.workspace }}:/src --interactive zricethezav/gitleaks detect --source=/src --verbose --no-git --report-path gitleaks-reports.json
      - name: cat file
        if: always()
        run: cat gitleaks-reports.json
      - name: move file
        if: always()
        run: cp gitleaks-reports.json  ${{ github.workspace }}/gitleaks-reports.json     
      - name: upload_artifacts   
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path:  ${{ github.workspace }}/gitleaks-reports.json
            
            
            
            
   
       
