name: TruffleHog Secrets Scan
on: [push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout 
        uses: addnab/docker-run-action@v3
        with:
          image: zricethezav/gitleaks
          shell: bash
          options: --user $(id -u):$(id -g) -v ${{ github.workspace }}:/src
          run: |
            gitleaks detect --source=. --verbose --no-git --report-path=gitleaks-reports.json
   
       
