name: TruffleHog Secrets Scan
on: [push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout
        run: |
            docker run --user root --volume ${github.workspace}:/ --interactive zricethezav/gitleaks detect --source=/src --verbose --no-git --report-path /home/runner/work/WebGoat/WebGoat/gitleaks-reports.json
      - name: tade
        if: always()
        run: ls
      - name: upload_artifacts   
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path:  ${{ github.workspace }}/gitleaks-reports.json
            
            
            
            
   
       
