name: Gitleaks Secrets Scan
on: [push]
jobs:
  Credentials_Scanning:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks from container
        run: |
            docker create --name GitLeaksContainer --entrypoint /bin/bash --interactive --volume ${{ github.workspace }}:/new_folder zricethezav/gitleaks 
            docker start GitLeaksContainer
            docker exec GitLeaksContainer id && docker exec GitLeaksContainer whoami
            docker exec GitLeaksContainer git config --global --add safe.directory '/new_folder'
            docker exec GitLeaksContainer gitleaks detect --source=/new_folder --verbose -c /src/gitleaks.toml --report-path /src/gitleaks-reports.json
        continue-on-error: true

      - name: upload_artifacts   
        uses: actions/upload-artifact@v3
        with:
          name: Gitleaks Artifact Upload
          path:  ${{ github.workspace }}/gitleaks-reports.json
